const root=document.getElementById('root');
const state={screen:'intro',q:0,lives:3,answered:false,streak:0,score:0,time:18,timer:null,sound:true,travel:false};
const wrongLines=[
  'Areee Pihu… main thoda aur neeche aa gaya 😭 Jaldi mujhe bacha lo!',
  'Mujhe laga tumhe yeh yaad hoga… par koi nahi, main abhi bhi wait kar raha hoon 🥺',
  'Ouch 💀 web slip ho gaya… ek aur try, meri hero!',
  'Main gir toh raha hoon… par trust tum par hi hai ❤️',
  'Pihu pleaseee, mujhe villain se nahi tumhari memory se darr lag raha hai 😭'
];
const questions=[
{scene:'city',q:'Hum pehli baar kab mile the?',options:['26 December 2022','5 March 2023','8 September 2023','13 December 2024'],answer:0,date:'26 December 2022',title:'Jab hum pehli baar mile',detail:'Uss din shayad hume bilkul idea nahi tha ki yeh ek normal meeting nahi rehne wali. Mujhe nahi pata tha ki ek din tum meri favourite person ban jaogi.'},
{scene:'call',q:'Humne numbers kab exchange kiye the?',options:['26 December 2022','5 March 2023','23 May 2025','8 September 2023'],answer:1,date:'5 March 2023',title:'Finally number mil gaya',detail:'Ussi din humne numbers exchange kiye… aur haan, finally tumhara poora naam bhi pata chala. Story yahin se thodi aur real hone lagi.'},
{scene:'call',q:'Hamari pehli phone call mein tum aur didi kya kar rahe the?',options:['Birthday plan bana rahe the','Mujhe lecture de rahe the','Ek ladki bankar prank kar rahe the','Song ga rahe the'],answer:2,date:'8 September 2023',title:'Hamari pehli phone call',detail:'Tum aur didi milkar mujhe bewakoof bana rahe the, kisi aisi ladki bankar jisko supposedly mujh mein romantic interest tha. Aur main genuinely confuse ho gaya tha 💀'},
{scene:'rooftop',q:'Hum officially dating kab start hue?',options:['13 December 2024','23 May 2025','5 March 2023','26 December 2022'],answer:0,date:'13 December 2024',title:'The day we became us',detail:'Iss din maine tumhe propose kiya… aur hum officially dating start kar diye. Honestly, meri life ke best decisions mein se ek.'},
{scene:'park',q:'Deer Park wali legendary misunderstanding mein tumne kya bola tha?',options:['Should I?','Shirt','Shh','Sure?'],answer:1,date:'23 May 2025 · Deer Park',title:'Shirt?',detail:'Shaam thi, park almost khaali tha, aur tumne dheere se “shirt” bola. Mujhe “should I?” sunayi diya… maine pooch liya “Are you sure?” Phir embarrassment hide karne ke liye weather ki baat karne laga 💀 Uske baad 3… 2… 1… GO ❤️'},
{scene:'park',q:'Mujhe tease karne ke liye tumne kaunsa gaana bheja tha?',options:['Lag Ja Gale','Buddha Mil Gaya','Pehla Nasha','Pal Pal Dil Ke Paas'],answer:1,date:'The official teasing anthem',title:'Mujhe buddha mil gaya?',detail:'Dating start hone ke baad tumne “Mai Kya Karu Haaye Mujhe Buddha Mil Gaya” bheja—sirf isliye kyunki main kabhi kabhi zyada mature act karta hoon aur meri taste supposedly old hai. Accha ji… itna bhi buddha nahi hoon.'}
];
function tone(freq=440,dur=.12,type='sine',gain=.05){if(!state.sound)return;try{const A=window.AudioContext||window.webkitAudioContext;const c=tone.ctx||(tone.ctx=new A());const o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+dur);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+dur)}catch(e){}}
function successSound(){tone(523,.12,'sine',.06);setTimeout(()=>tone(659,.12,'sine',.06),110);setTimeout(()=>tone(784,.22,'sine',.07),220)}
function failSound(){tone(220,.18,'sawtooth',.045);setTimeout(()=>tone(165,.32,'sawtooth',.04),150)}
function kissSound(){[523,659,784,1046].forEach((f,i)=>setTimeout(()=>tone(f,.28,'sine',.05),i*100))}
function kittySVG(expr='happy'){const sad=expr==='sad',blush=expr==='blush';return `<div class="character kitty-idle ${sad?'kitty-sad':''} ${blush?'blush':''}"><svg viewBox="0 0 180 220" aria-label="cute white kitty hero"><ellipse cx="90" cy="194" rx="47" ry="16" fill="#0003"/><path d="M54 56 38 22 72 42M126 56l16-34-34 20" fill="#fff" stroke="#2b2130" stroke-width="5" stroke-linejoin="round"/><ellipse cx="90" cy="78" rx="59" ry="51" fill="#fff" stroke="#2b2130" stroke-width="5"/><ellipse cx="70" cy="77" rx="5" ry="8" fill="#2b2130"/><ellipse cx="112" cy="77" rx="5" ry="8" fill="#2b2130"/><ellipse cx="91" cy="91" rx="7" ry="5" fill="#ffd54d" stroke="#2b2130" stroke-width="2"/>${sad?'<path d="M79 108q12-10 24 0" fill="none" stroke="#2b2130" stroke-width="4"/><path d="M67 87q-7 14 0 24" fill="none" stroke="#75c9ff" stroke-width="5"/>':'<path d="M78 105q13 12 27 0" fill="none" stroke="#2b2130" stroke-width="4"/>'}${blush?'<ellipse cx="57" cy="98" rx="12" ry="6" fill="#ff8cab" opacity=".8"/><ellipse cx="123" cy="98" rx="12" ry="6" fill="#ff8cab" opacity=".8"/>':''}<g fill="none" stroke="#2b2130" stroke-width="3"><path d="M52 88 18 82M52 98 17 103M128 88l34-6M128 98l35 5"/></g><path d="M126 47c11-15 27-10 27 3 0 12-14 17-27 8-13 9-27 4-27-8 0-13 16-18 27-3Z" fill="#ff6faa" stroke="#2b2130" stroke-width="4"/><path d="M59 125q31-17 62 0l12 60H47z" fill="#ff78b7" stroke="#2b2130" stroke-width="5"/><path d="M57 139 28 164M123 139l29 25M69 184l-8 25M111 184l8 25" stroke="#2b2130" stroke-width="7" stroke-linecap="round"/></svg></div>`}
function spideySVG(mode='hang'){const cls=mode==='fall'?'spidey-fall':mode==='cry'?'spidey-cry':mode==='blush'?'spidey-blush':'spidey-hang';return `<div class="character ${cls}"><div class="webline"></div><svg viewBox="0 0 180 220" aria-label="masked web hero"><ellipse cx="90" cy="201" rx="42" ry="13" fill="#0003"/><ellipse cx="90" cy="61" rx="39" ry="43" fill="#e83b51" stroke="#181521" stroke-width="5"/><path d="M63 51q12-13 20 4-9 31-25 8Zm54 0q-12-13-20 4 9 31 25 8Z" fill="#fff" stroke="#181521" stroke-width="4"/>${mode==='blush'?'<ellipse cx="55" cy="82" rx="11" ry="6" fill="#ff9ab6"/><ellipse cx="125" cy="82" rx="11" ry="6" fill="#ff9ab6"/>':''}<path d="M90 19v83M54 41l72 42M126 41 54 83M51 62h78" stroke="#181521" stroke-width="2" opacity=".65"/><path d="M61 103q29-18 58 0l15 68-29 20H75l-29-20z" fill="#e83b51" stroke="#181521" stroke-width="5"/><path d="M61 111 43 174M119 111l18 63M72 181l-9 29M108 181l9 29" stroke="#173c78" stroke-width="18" stroke-linecap="round"/><path d="M90 115c-9 8-8 18 0 22 8-4 9-14 0-22Zm0 22-13 18m13-18 13 18m-13-9v25" stroke="#181521" stroke-width="3" fill="none"/>${mode==='cry'?'<path class="tear" d="M69 72q-8 17 0 31M111 72q8 17 0 31" stroke="#75c9ff" stroke-width="6" fill="none"/>':''}</svg></div>`}
function sceneDecor(scene){return `<div class="parallax far"></div><div class="parallax near"></div><div class="moon"></div><div class="cloud" style="top:18%"></div><div class="cloud" style="top:34%;animation-delay:-9s;opacity:.55"></div>${scene==='city'||scene==='call'||scene==='rooftop'?'<div class="cityline"></div>':''}${scene==='park'?'<div class="tree" style="left:4%"></div><div class="tree" style="right:5%;height:270px"></div><div class="bench"></div>':''}<div class="road"></div>`}
function clearTimer(){if(state.timer){clearInterval(state.timer);state.timer=null}}
function startTimer(){clearTimer();state.time=18;state.timer=setInterval(()=>{state.time--;const t=document.getElementById('time');if(t)t.textContent=state.time;if(state.time<=0){clearTimer();wrongAnswer(null,true)}},1000)}
function render(){clearTimer();if(state.screen==='intro')return intro();if(state.screen==='travel')return travel();if(state.screen==='game')return game();if(state.screen==='final')return final();}
function intro(){root.innerHTML=`<main class="app"><div class="stars"></div><button class="sound-toggle" id="sound">${state.sound?'🔊':'🔇'}</button><section class="screen"><div class="panel"><p class="kicker">Pihu turns 20 · Rescue Mission</p><h1 class="title"><span>Hello Kitty</span><br>to the Rescue</h1><p class="lead">Spider-Man phas gaya hai. Har sahi answer tumhe uske aur paas le jayega. Galat answer par woh girta hai, rota hai… aur tum ek life lose karti ho 💀</p><div class="duo">${kittySVG()}<div style="font-size:42px">💗</div>${spideySVG()}</div><button class="cta" id="start">Start rescue 🎀</button></div></section></main>`;document.getElementById('start').onclick=()=>{tone(440,.1);state.screen='travel';render()};document.getElementById('sound').onclick=()=>{state.sound=!state.sound;render()}}
function travel(){const item=questions[state.q];root.innerHTML=`<main class="app"><div class="stars"></div><section class="screen"><div class="mission"><div class="hud"><span>Traveling to memory ${state.q+1}</span><span>${'❤️'.repeat(state.lives)}</span></div><div class="scene ${item.scene} traveling">${sceneDecor(item.scene)}<div class="travel-kitty">${kittySVG()}</div><div class="sign">${item.scene==='park'?'Deer Park':'Memory '+(state.q+1)} →</div><div class="travel-text">Run Pihu, run! 🎀</div></div></div></section></main>`;setTimeout(()=>{state.screen='game';render()},1900)}
function game(){const item=questions[state.q];const pct=Math.round(state.q/questions.length*100);root.innerHTML=`<main class="app"><div class="stars"></div><button class="sound-toggle" id="sound">${state.sound?'🔊':'🔇'}</button><section class="screen"><div class="mission"><div class="hud"><span>Level ${state.q+1}/${questions.length} · Score ${state.score} · Streak ${state.streak}🔥</span><span class="lives">${'❤️'.repeat(state.lives)}${'🖤'.repeat(3-state.lives)} · ⏱ <b id="time">18</b>s</span></div><div class="progress"><i style="width:${pct}%"></i></div><div class="scene ${item.scene}" id="scene">${sceneDecor(item.scene)}<div class="rescue-stage"><div id="kitty" class="kitty-position">${kittySVG()}</div><div id="spidey">${spideySVG()}</div></div><div class="quiz-card" id="quiz"><p class="kicker">Memory Check</p><h2>${item.q}</h2><div class="choices">${item.options.map((o,i)=>`<button class="choice" data-i="${i}">${o}</button>`).join('')}</div></div></div></div></section></main>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>answer(+b.dataset.i,b));document.getElementById('sound').onclick=()=>{state.sound=!state.sound;document.getElementById('sound').textContent=state.sound?'🔊':'🔇'};startTimer()}
function answer(i,btn){if(state.answered)return;state.answered=true;clearTimer();const item=questions[state.q];if(i===item.answer){btn.classList.add('correct');state.streak++;state.score+=100+(state.time*5)+(state.streak*20);successSound();document.getElementById('kitty').classList.add('kitty-celebrate');setTimeout(()=>reveal(item),650)}else wrongAnswer(btn,false)}
function wrongAnswer(btn,timed){if(state.answered&&!timed&&btn===null)return;state.answered=true;clearTimer();if(btn)btn.classList.add('wrong');state.lives--;state.streak=0;failSound();const line=wrongLines[(state.q+state.lives)%wrongLines.length];document.getElementById('kitty').innerHTML=kittySVG('sad');document.getElementById('spidey').innerHTML=spideySVG('fall');document.getElementById('quiz').classList.add('quiz-drop');const scene=document.getElementById('scene');const bubble=document.createElement('div');bubble.className='emotional-line';bubble.innerHTML=`<b>${timed?'Time up! ⏰':'Wrong answer 💔'}</b><span>${line}</span>`;scene.appendChild(bubble);setTimeout(()=>{if(state.lives<=0){state.lives=3;state.q=0;state.score=0;state.streak=0;state.answered=false;state.screen='travel';render()}else{state.answered=false;state.screen='travel';render()}},2600)}
function reveal(item){const host=document.getElementById('scene');const layer=document.createElement('div');layer.className='memory-reveal';layer.innerHTML=`<article class="memory-card"><div class="cute-break">✨ 🎀 💗</div><p class="date">${item.date}</p><h2>${item.title}</h2><p>${item.detail}</p>${item.title==='Shirt?'?'<div class="count">3… 2… 1… GO ❤️</div>':''}<button class="cta" id="next">Next destination</button></article>`;host.appendChild(layer);document.getElementById('next').onclick=()=>{state.q++;state.answered=false;if(state.q>=questions.length){state.screen='final'}else state.screen='travel';render()}}
function confetti(){const wrap=document.createElement('div');wrap.className='confetti-wrap';for(let i=0;i<120;i++){const c=document.createElement('i');c.style.left=Math.random()*100+'%';c.style.animationDelay=(Math.random()*2)+'s';c.style.setProperty('--r',(Math.random()*720-360)+'deg');c.textContent=['💗','✨','🎀','💖','🌸'][i%5];wrap.appendChild(c)}document.body.appendChild(wrap);setTimeout(()=>wrap.remove(),7000)}
function final(){root.innerHTML=`<main class="app finale"><div class="stars"></div><section class="screen final-screen"><div class="mission"><div class="scene rooftop final-scene">${sceneDecor('rooftop')}<div class="final-web fire"></div><div class="final-stage"><div class="final-kitty">${kittySVG('blush')}</div><div class="final-spidey">${spideySVG('blush')}</div><div class="kiss-heart">💗</div></div><div class="speech final-speech">Tum aa gayi… meri hero 🥹</div><div class="victory-banner">MISSION COMPLETE · SCORE ${state.score}</div><button class="cta reveal-letter" id="letterBtn">Open birthday letter 💌</button><div class="letter-overlay hidden" id="letterOverlay"><article class="letter"><p class="kicker">Mission complete</p><h2>Spider-Man saved. Birthday girl victorious. 💗</h2><p>Ab yahan tumhara final birthday letter appear hoga. Pehle tumne har memory cross ki, phir mujhe bachaya… aur ab bas tum aur main.</p><button class="cta" id="again">Play again</button></article></div></div></div></section></main>`;confetti();kissSound();document.getElementById('letterBtn').onclick=()=>document.getElementById('letterOverlay').classList.remove('hidden');setTimeout(()=>{const h=document.querySelector('.kiss-heart');if(h)h.classList.add('show')},1900);setTimeout(()=>kissSound(),1800);document.addEventListener('click',function once(e){if(e.target&&e.target.id==='again'){state.screen='intro';state.q=0;state.lives=3;state.score=0;state.streak=0;state.answered=false;render()}},{once:false})}
render();