(()=>{'use strict';
const root=document.getElementById('root');
const S={q:0,l:3,c:0,score:0,sound:true,a:null,m:false,mt:null,x:6,open:false,collect:false,keys:{},loop:null};
const Q=[
{scene:'city',q:'Hum pehli baar December mein kis date ko mile the?',o:['24 December','25 December','26 December','28 December'],a:2,date:'26 December 2022',title:'Jab hum pehli baar mile',detail:'Wahi din jisne ek normal December ko quietly special bana diya.'},
{scene:'city',q:'26 December wali pehli meeting ko main kaise yaad karta hoon?',o:['Ek random awkward hi-hello','Hamari story ka first page','Official proposal day','Deer Park ka funny moment'],a:1,date:'26 December 2022',title:'Hamari story ka first page',detail:'Mere liye woh sirf pehli meeting nahi thi, wahi se hamari story ka first page start hua.'},
{scene:'call',q:'Humne March mein kis date ko numbers exchange kiye the?',o:['3 March','5 March','6 March','8 March'],a:1,date:'5 March 2023',title:'Finally, tera number mil gaya',detail:'Ussi din humne numbers exchange kiye aur story thodi aur real ho gayi.'},
{scene:'call',q:'Hamari pehli phone call kis month mein hui thi?',o:['August','September','October','November'],a:1,date:'8 September 2023',title:'Hamari pehli call',detail:'Aur woh bhi koi seedhi-saadhi call nahi thi, us din meri confusion legendary level par thi 💀'},
{scene:'call',q:'Pehli phone call ke baad meri halat kaisi thi?',o:['Bilkul normal','Genuinely confused','Full angry','Seedha sleepy'],a:1,date:'8 September 2023',title:'Confusion pro max',detail:'Tune aur didi ne scene itna convincing banaya ki main sach mein confuse ho gaya tha.'},
{scene:'rooftop',q:'Hum officially dating December mein kis date ko start hue?',o:['11 December','12 December','13 December','14 December'],a:2,date:'13 December 2024',title:'Jis din hum “hum” bane',detail:'Iss din maine tujhe propose kiya aur hum officially dating start hue.'},
{scene:'rooftop',q:'Hamari timeline ka sahi order kaunsa hai?',o:['Pehli call → numbers → dating','Numbers → pehli meeting → dating','Pehli meeting → numbers → pehli call → dating','Dating → pehli call → numbers'],a:2,date:'Hamari timeline',title:'Tune poori timeline jod di',detail:'Pehle hum mile, phir numbers, phir prank call, aur phir officially hum.'},
{scene:'park',q:'Deer Park wali misunderstanding mein tune exactly kya bola tha?',o:['Should I?','Shirt','Sure?','Shh'],a:1,date:'23 May 2025 · Deer Park',title:'“Shirt?”',detail:'Tune “shirt” bola, mujhe “should I?” sunayi diya, aur main “Are you sure?” bolkar khud hi phas gaya 💀'},
{scene:'park',q:'Deer Park wale moment ke baad countdown kya tha?',o:['5… 4… 3… GO','3… 2… 1… GO','1… 2… 3… GO','Ready… set… GO'],a:1,date:'23 May 2025',title:'3… 2… 1… GO ❤️',detail:'Thodi embarrassment ke baad bhi tune uss moment ko legendary bana diya.'},
{scene:'park',q:'Buddha Mil Gaya bhejne ka tera asli mission kya tha?',o:['Mujhe old-school romantic bolna','Mujhe buddha tease karna','Meri singing test karna','Mujhe dance karwana'],a:1,date:'Hamari teasing anthem',title:'“Mujhe Buddha Mil Gaya”',detail:'Gaana toh tujhe pata hi tha, par uska asli kaam mujhe cute tareeke se buddha bolna tha. Accha ji, itna bhi buddha nahi hoon 😭'}];
const intro=['Ek shaant raat thi. Hello Kitty apni birthday walk par nikli thi… 🎀','Tabhi aasman se ek tooti hui spider-web uske paas aa kar giri.','Memory Monster ne Spider-Man ko pakad liya tha aur hamari yaadon ko 10 crystals mein tod diya tha.','“Pihu! Agar yaadein wapas nahi aayi, toh meri web toot jayegi…”','Ab sirf tu hi har memory wapas laa kar Spider-Man ko bacha sakti hai.','Chal Pihu. Ab tu khud Hello Kitty ko chala kar mere paas aayegi. 💗'];
const wrong=['Areee Pihu… web aur slip ho gayi 😭','Mujhe laga tujhe yeh yaad hoga… koi nahi, ek aur try kar 🥺','Main gir raha hoon, par mujhe abhi bhi tujh par trust hai ❤️','Memory Monster aur strong ho raha hai… jaldi kar!','Nooo, yeh meri favourite memories mein se ek thi 😭'];
function kitty(bl=false){return `<div class="char"><svg viewBox="0 0 180 220"><ellipse cx="90" cy="194" rx="47" ry="16" fill="#0003"/><path d="M54 56 38 22 72 42M126 56l16-34-34 20" fill="#fff" stroke="#2b2130" stroke-width="5"/><ellipse cx="90" cy="78" rx="59" ry="51" fill="#fff" stroke="#2b2130" stroke-width="5"/><ellipse cx="70" cy="77" rx="5" ry="8"/><ellipse cx="112" cy="77" rx="5" ry="8"/><ellipse cx="91" cy="91" rx="7" ry="5" fill="#ffd54d"/>${bl?'<ellipse cx="57" cy="98" rx="12" ry="6" fill="#ff8cab"/><ellipse cx="123" cy="98" rx="12" ry="6" fill="#ff8cab"/>':''}<path d="M78 105q13 12 27 0" fill="none" stroke="#2b2130" stroke-width="4"/><path d="M126 47c11-15 27-10 27 3 0 12-14 17-27 8-13 9-27 4-27-8 0-13 16-18 27-3Z" fill="#ff6faa" stroke="#2b2130" stroke-width="4"/><path d="M59 125q31-17 62 0l12 60H47z" fill="#ff78b7" stroke="#2b2130" stroke-width="5"/><path d="M57 139 28 164M123 139l29 25M69 184l-8 25M111 184l8 25" stroke="#2b2130" stroke-width="7" stroke-linecap="round"/></svg></div>`}
function spidey(bl=false){return `<div class="char"><svg viewBox="0 0 180 220"><ellipse cx="90" cy="201" rx="42" ry="13" fill="#0003"/><ellipse cx="90" cy="61" rx="39" ry="43" fill="#e83b51" stroke="#181521" stroke-width="5"/><path d="M63 51q12-13 20 4-9 31-25 8Zm54 0q-12-13-20 4 9 31 25 8Z" fill="#fff" stroke="#181521" stroke-width="4"/>${bl?'<ellipse cx="55" cy="82" rx="11" ry="6" fill="#ff9ab6"/><ellipse cx="125" cy="82" rx="11" ry="6" fill="#ff9ab6"/>':''}<path d="M90 19v83M54 41l72 42M126 41 54 83M51 62h78" stroke="#181521" stroke-width="2"/><path d="M61 103q29-18 58 0l15 68-29 20H75l-29-20z" fill="#e83b51" stroke="#181521" stroke-width="5"/><path d="M61 111 43 174M119 111l18 63M72 181l-9 29M108 181l9 29" stroke="#173c78" stroke-width="18" stroke-linecap="round"/></svg></div>`}
function decor(scene){return `<div class="world ${scene}"><div class="moon"></div><div class="cloud" style="top:18%"></div><div class="cloud" style="top:34%;animation-delay:-8s;opacity:.55"></div>${scene==='park'?'<div class="tree" style="left:5%"></div><div class="tree" style="right:6%;height:255px"></div>':'<div class="buildings"></div>'}<div class="road"></div></div>`}
function tone(f,d=.15,type='sine',g=.045){if(!S.sound)return;try{const A=window.AudioContext||window.webkitAudioContext,c=S.a||(S.a=new A()),o=c.createOscillator(),v=c.createGain();o.type=type;o.frequency.value=f;v.gain.setValueAtTime(g,c.currentTime);v.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(v);v.connect(c.destination);o.start();o.stop(c.currentTime+d)}catch{}}
function music(){if(!S.sound||S.m)return;S.m=true;let n=0,a=[261.6,329.6,392,329.6,293.7,349.2,440,349.2];S.mt=setInterval(()=>tone(a[n++%a.length],.55,'sine',.018),520)}
function stopMusic(){clearInterval(S.mt);S.mt=null;S.m=false}
document.getElementById('sound').onclick=()=>{S.sound=!S.sound;document.getElementById('sound').textContent=S.sound?'🔊':'🔇';S.sound?music():stopMusic()};
function introScreen(){root.innerHTML=`<main class="app"><section class="screen"><div class="panel"><p class="k">Pihu turns 20</p><h1 class="title"><span>Hello Kitty</span><br>to the Rescue</h1><p class="lead">Iss baar tu sirf answers nahi degi. Tu Hello Kitty ko khud chala kar har obstacle cross karegi aur Spider-Man tak pahuchegi.</p><div class="duo">${kitty()}<div style="font-size:48px">💗</div>${spidey()}</div><button class="cta" id="begin">Story shuru kar 🎀</button></div></section></main>`;document.getElementById('begin').onclick=()=>{music();cut(0)}}
function cut(i){if(i>=intro.length)return brief();root.innerHTML=`<main class="app"><section class="screen"><div class="panel"><p class="k">Ek chhoti si kahani…</p><div class="story" style="font-size:clamp(1.3rem,3vw,2rem);min-height:150px;display:grid;place-items:center">${intro[i]}</div><button class="cta" id="next">${i===intro.length-1?'Mission shuru kar':'Aage'}</button></div></section></main>`;document.getElementById('next').onclick=()=>cut(i+1)}
function brief(){root.innerHTML=`<main class="app"><section class="screen"><div class="panel"><p class="k">Controls</p><h1>Kitty ko tu chalayegi 🎀</h1><p class="lead">Laptop par <b>← →</b> ya <b>A D</b> use kar. Mobile par neeche ke buttons daba. Gate ke paas pahunchte hi sawaal khulega. Sahi answer ke baad crystal ko touch karke collect kar.</p><div style="font-size:2rem;margin:24px 0">⬅️ Kitty ➡️ &nbsp; 🔒 &nbsp; 💎</div><button class="cta" id="go">Chal, mujhe bacha le</button></div></section></main>`;document.getElementById('go').onclick=level}
function level(){clearInterval(S.loop);S.x=6;S.open=false;S.collect=false;const x=Q[S.q];root.innerHTML=`<main class="app"><section class="screen"><div class="mission"><div class="hud"><span>Yaad ${S.q+1}/10 · Score ${S.score}</span><span>💎 ${S.c}/10 · ${'❤️'.repeat(S.l)}${'🖤'.repeat(3-S.l)}</span></div><div class="stage" id="stage">${decor(x.scene)}<div class="hint">Gate tak jaa — phir dekhte hain tujhe kitna yaad hai 😌</div><div class="dialogue">${S.q<3?'Pihuuuu, idhar aa! 😭':S.q<7?'Tu paas aa rahi hai… jaldi!':'Bas thoda aur… mujhe pata hai tu kar legi ❤️'}</div><div class="player" id="player">${kitty()}</div><div class="obstacle" id="obstacle"><div class="gate"></div></div><div class="crystal hidden" id="crystal">💎</div><div class="controls"><div class="pad"><button class="ctrl" id="left">⬅️</button><button class="ctrl" id="right">➡️</button></div><div class="pad"><button class="ctrl action" id="action">Gate kholo</button></div></div></div></div></section></main>`;bindControls();S.loop=setInterval(step,16)}
function bindControls(){const down=(k)=>{S.keys[k]=true},up=(k)=>{S.keys[k]=false};window.onkeydown=e=>{if(['ArrowLeft','ArrowRight','a','A','d','D'].includes(e.key)){e.preventDefault();down(e.key)}};window.onkeyup=e=>up(e.key);[['left','ArrowLeft'],['right','ArrowRight']].forEach(([id,k])=>{const b=document.getElementById(id);b.onpointerdown=e=>{e.preventDefault();down(k)};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>up(k)});document.getElementById('action').onclick=interact}
function step(){const p=document.getElementById('player');if(!p)return;let dx=0;if(S.keys.ArrowLeft||S.keys.a||S.keys.A)dx=-.45;if(S.keys.ArrowRight||S.keys.d||S.keys.D)dx=.45;const max=S.open?88:67;S.x=Math.max(2,Math.min(max,S.x+dx));p.style.left=S.x+'%';p.classList.toggle('running',dx!==0);if(!S.open&&S.x>=65)interact();if(S.open&&!S.collect&&S.x>=84)collectCrystal()}
function interact(){if(S.open)return;showQuestion()}
function showQuestion(){clearInterval(S.loop);const x=Q[S.q],stage=document.getElementById('stage');const u=document.createElement('div');u.className='ui';u.id='quiz';u.innerHTML=`<div class="card"><p class="k">Memory gate</p><h2>${x.q}</h2><div class="choices">${x.o.map((v,i)=>`<button class="choice" data-i="${i}">${v}</button>`).join('')}</div></div>`;stage.appendChild(u);u.querySelectorAll('.choice').forEach(b=>b.onclick=()=>answer(+b.dataset.i,b))}
function answer(i,b){const x=Q[S.q];if(i===x.a){b.classList.add('correct');S.score+=100;[523,659,784].forEach((f,j)=>setTimeout(()=>tone(f,.18),j*90));setTimeout(()=>{document.getElementById('quiz').remove();S.open=true;document.getElementById('obstacle').animate([{opacity:1,transform:'translateY(0)'},{opacity:0,transform:'translateY(-140px)'}],{duration:700,fill:'forwards'});document.getElementById('crystal').classList.remove('hidden');document.querySelector('.hint').textContent='Gate khul gaya! Ab crystal collect kar 💎';S.loop=setInterval(step,16)},650)}else{b.classList.add('wrong');S.l--;tone(200,.3,'sawtooth');const card=b.closest('.card');card.innerHTML=`<h2>Galat jawab 💔</h2><p>${wrong[S.q%wrong.length]}</p><button class="cta" id="retry">Ek aur try</button>`;if(S.l<=0){S.l=3;S.score=Math.max(0,S.score-100)}document.getElementById('retry').onclick=()=>{document.getElementById('quiz').remove();S.loop=setInterval(step,16)}}}
function collectCrystal(){S.collect=true;clearInterval(S.loop);S.c++;const x=Q[S.q],cr=document.getElementById('crystal');cr.animate([{transform:'scale(1)',opacity:1},{transform:'translate(-50vw,-40vh) scale(2)',opacity:0}],{duration:800,fill:'forwards'});setTimeout(()=>memoryReveal(x),650)}
function memoryReveal(x){const stage=document.getElementById('stage'),u=document.createElement('div');u.className='ui';u.innerHTML=`<div class="card"><div style="font-size:3rem">💎✨</div><p class="k">Yaad wapas aa gayi</p><h2>${x.title}</h2><p><b>${x.date}</b></p><p>${x.detail}</p><button class="cta" id="continue">${S.q===9?'Ab mujhe bacha le':'Agli yaad ki taraf'}</button></div>`;stage.appendChild(u);document.getElementById('continue').onclick=()=>{S.q++;S.q>=10?finale():level()}}
function finale(){clearInterval(S.loop);root.innerHTML=`<main class="app"><section class="screen"><div class="mission"><div class="stage" id="final">${decor('rooftop')}<div class="caption" id="finalCaption">Tune saari yaadein wapas laa di 💗</div><svg class="websvg" viewBox="0 0 1000 650" preserveAspectRatio="none" aria-hidden="true"><path id="web" class="webpath" d="M820 400 L170 400"/></svg><div class="hero kitty" id="fk">${kitty(true)}</div><div class="hero spidey" id="fs">${spidey(true)}</div><div class="heart" id="heart">💗</div><button class="cta letterbtn" id="letter" type="button">Apna birthday letter khol 💌</button></div></div></section></main>`;const final=document.getElementById('final'),caption=document.getElementById('finalCaption'),letter=document.getElementById('letter');const say=t=>{if(caption)caption.textContent=t};setTimeout(()=>{say('Kuku ne web shoot kiya 🕸️');final.classList.add('web-shot')},300);setTimeout(()=>{say('Hello Kitty seedha Kuku ke paas aa rahi hai 💗');final.classList.add('pull-kitty')},1200);setTimeout(()=>{say('Finally together 💗');final.classList.add('hug-ready');document.getElementById('heart').classList.add('pop');[523,659,784,1046].forEach((f,i)=>setTimeout(()=>tone(f,.25),i*90));confetti()},3000);setTimeout(()=>letter.classList.add('show'),3900);letter.onclick=()=>{if(document.getElementById('letterPopup'))return;const u=document.createElement('div');u.className='ui letter-ui';u.id='letterPopup';u.innerHTML=`<div class="card letter-card"><p class="k">Meri Pihu ke liye</p><h2>Happy Birthday, meri cutest hero 💗</h2><p>Pihu, aaj tera din hai, aur honestly mujhe bas itna bolna hai ki tu meri life ka woh part hai jahan sab kuch thoda zyada soft, thoda zyada funny, aur bohot zyada special lagta hai.</p><p>26 December se lekar aaj tak, har chhoti memory mere liye important hai. Teri hasi, tera drama, teri teasing, aur woh moments jahan hum bina kuch bole bhi ek dusre ko samajh lete hain, sab mere favourite hain.</p><p>Tu kabhi Hello Kitty jaisi cute hai, kabhi meri full hero, aur kabhi woh pagal si ladki jo mujhe Buddha Mil Gaya bhej kar khud hi hans leti hai. Par in sab versions mein ek cheez same hai: tu meri Pihu hai, aur main bohot lucky hoon.</p><p>Iss birthday par meri wish hai ki tu hamesha aise hi smile kare, khud par proud feel kare, aur tujhe woh saara pyaar mile jo tu deserve karti hai. Main hamesha tere side mein rahunga, chahe memory gate ho, misunderstanding ho, ya life ka koi bhi level.</p><p>Happy 20th birthday, Pihu. I love you bohot saara. Aaj, kal, aur har naye level mein. 💌</p><button class="cta" id="again" type="button">Phir se khel</button></div>`;final.appendChild(u);document.getElementById('again').onclick=()=>{Object.assign(S,{q:0,l:3,c:0,score:0,x:6,open:false,collect:false,keys:{}});introScreen()}}}
function confetti(){for(let i=0;i<120;i++){const p=document.createElement('div');p.textContent=['💗','🎀','✨','🌸'][i%4];Object.assign(p.style,{position:'fixed',left:Math.random()*100+'vw',top:'-50px',zIndex:999,fontSize:(15+Math.random()*22)+'px',pointerEvents:'none'});document.body.appendChild(p);p.animate([{transform:'translateY(0) rotate(0)'},{transform:'translateY(112vh) rotate(900deg)'}],{duration:3200+Math.random()*2600,delay:Math.random()*1000,easing:'linear'});setTimeout(()=>p.remove(),7000)}}
introScreen();
})();
